### ISSUE TITLE
[PROPOSAL] New format

### ISSUE THREAD

**Issue by fallion** [commitsar-app/release-notary#132]
From the current format I would like to upgrade to something more complex.

- Features and breaking changes should be un-collapsed by default
- Everything else should have collapsed commit body

# Example:

# Features 🚀 

<details open>
<summary>hash some feature</summary>

- body is here
</details>

# Chores 🔧 

<details>
<summary>hash heading</summary>

- body is here
</details>

hash commit without a body

<details>
<summary>hash another chore</summary>
<p> body is here </p>
</details>

**Comment by aexvir** [comment]
Will it still keep the bullet point list inside the collapsible blocks?

**Comment by fallion** [comment]
Turns out it will, https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab just updated the example.

**Comment by aexvir** [comment]
So any markdown in the description would be rendered properly, I like it 😄
